[project]
name = "exojit"
version = "0.1.0"
license-files = ["LICENSE"]
requires-python = "==3.14.*"
dependencies = [
    "exo-lang @ git+https://github.com/exo-lang/exo.git@ec75d3c5b229b1519890f836e7badcd46b04c007",
    "xdsl @ git+https://github.com/xdslproject/xdsl.git@ad4fb9c277a65993a1c988dfeea2b30c52b66db9",
    "click",
    "cffi",
    "lit",
    "filecheck",
    "numpy",
    "pytest",
    "pytest-xdist",
    "pytest-forked",
    "llvmlite",
    "plotnine",
    "polars",
    "pyarrow",
    "tqdm",
    "jax",
    "numba",
    "torch",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13"]
build-backend = "uv_build"

[tool.uv]
build-backend = { module-root = "", namespace = true }

[tool.pytest.ini_options]
addopts = "-n auto --forked -v"

[project.scripts]
exojit = "exojit:cli"
